project:
  type: website
  output-dir: docs
  
website:
  title: "STAT 5010: Bayesian Statistical Methods"
  navbar:
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        href: https://github.com/chun-hao/stat-5010
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Chun-Hao Yang"

format:
  html:
    theme: simplex
    toc: true

editor: source

