---
title: "Bayesian Statistical Methods (Fall 2023)"
---

## Course Schedule {.smaller}

| Week | Date  | Topics                                                    | Lecture                            | Reading                   |
|:------------:|--------------|-----------------|--------------|--------------|
|  1   | 9/5   | Introduction & History of Bayes Theorem                   | [Slide](slides/01-intro.qmd)       |                           |
|  2   | 9/12  | One-parameter Models; Conjugate Priors                    | [Slide](slides/02-intro-bayes.qmd) | Hoff Ch. 1-3, BC Ch. 1    |
|  3   | 9/19  | Prior Information and Prior Distribution                  | [Slide](slides/03-prior.qmd)       | BC Ch. 3                  |
|  4   | 9/26  | Decision Theory and Bayesian Estimation                   | [Slide](slides/04-estimation.qmd)  | BC Ch. 2, 4               |
|  5   | 10/3  | Connections to non-Bayesian Analysis; Hierarchical Models | [Slide](slides/05-hierarchical_model.qmd) | BDA Ch. 4, 5              |
|  6   | 10/10 | No class (National Holiday)                               |                                    |                           |
|  7   | 10/17 | Testing and Model Comparison                              | [Slide](slides/06-testing.qmd)     | BC Ch. 5, 7, BDA Ch. 6, 7 |
|  8   | 10/24 | Project Proposal                                          |                                    |                           |
|  9   | 10/31 | Metropolis-Hastings algorithms; Gibbs sampler             | [Slide](slides/07-mcmc.qmd)        | BDA Ch. 10-11             |
|  10  | 11/7  | Hamiltonian Monte Carlo; Variational Inference            | [Slide](slides/08-hmc_vb.qmd)      | BDA Ch. 12-13             |
|  11  | 11/14 | Bayesian regression                                       | [Slide](slides/09-regression.qmd)  | BDA Ch. 14                |
|  12  | 11/21 | Generalized Linear Models; Latent Variable Model |         [Slide](slides/10-glm.qmd) [Survey](slides/survey_example.qmd) | BDA Ch. 16, 18            |
|  13  | 11/28 | Gaussian Processes                                        | [Slide](slides/11-bayes_np.qmd)    | BDA Ch. 20, 21            |
|  14  | 12/5  | Dirichlet Processes                                       | [Slide](slides/12-dirichlet.qmd)   | BDA Ch. 22, 23            |
|  15  | 12/12 | Final Project Presentation                                |                                    |                           |
|  16  | 12/19 | Final Project Presentation                                |                                    |                           |

: {tbl-colwidths="\[5, 10, 60, 10, 25\]" .striped}

## Important Dates:

-   10/10: No class (National Holiday)
-   10/24: Project proposal: you need to prepare a 10-min presentation for your project proposal
-   12/12,19: Final project presentation: a 20-min presentation for your final project
